### ISSUE TITLE
Select which version of Logstash to install

### ISSUE THREAD

**Issue by driverpt** [geerlingguy/ansible-role-logstash#13]

**Comment by pabloalbrecht** [comment]
+1

**Comment by eli-betito** [comment]
I suffer from the same problem, is there a solution ?

**Comment by mgodlewski** [comment]
Done in https://github.com/mgodlewski/ansible-role-logstash/pull/5
and https://github.com/mgodlewski/ansible-role-logstash/pull/7

**Comment by geerlingguy** [comment]
I believe this has been fixed by a bit of a rewrite of the role (role version 4.0.0) to work with modern versions of logstash; see https://github.com/geerlingguy/ansible-role-logstash/commit/a1c342cc57c83d7ee8d1d87f340a11a7884b2405

Please re-open if you believe this issue is still relevant. Thanks!

(The new variable to control major version selection is `logstash_version`, which currently defaults to `'6.x'`.)
